services:
  backend:
    build:
      context: ./medusa-backend
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
      - "7001:7001"
    environment:
      - DATABASE_URL=postgres://TEST:TESTTEST@34.122.99.107:5432/medusa_db
      - JWT_SECRET=something
      - COOKIE_SECRET=something
      - DATABASE_TYPE=postgres
      - ADMIN_CORS=http://35.239.179.163:7700
      - STORE_CORS=http://35.239.179.163:8000,http://35.239.179.163:8100
      - NODE_ENV=development
      - HOST=0.0.0.0
    volumes:
      - ./medusa-backend:/app/backend
      - /app/backend/node_modules
      - backend-dist:/app/backend/dist

    networks:
      - medusa-network
    restart: unless-stopped
  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile
    image: admin:latest
    restart: always
    depends_on:
      - backend
    container_name: medusa-admin
    ports:
      - "7700:7700"
    environment:
      MEDUSA_BACKEND_URL: http://35.239.179.163:9000
      NODE_OPTIONS: --openssl-legacy-provider
    networks:
      - medusa-network

  storefront:
    build:
      context: ./storefront
      dockerfile: Dockerfile
    ports:
      - "8100:8100"
    environment:
      - NEXT_PUBLIC_MEDUSA_BACKEND_URL=http://35.239.179.163:9000
      - NEXT_PUBLIC_MEDUSA_API_KEY=pk_01JBB9STPSNXS0ZGFEQ7VDGB5T
      - REVALIDATE_WINDOW=10
      - NODE_ENV=development
    volumes:
      - ./storefront:/app/storefront
      - /app/storefront/node_modules
      - /app/storefront/.next
    depends_on:
      - backend
    networks:
      - medusa-network
    restart: unless-stopped
networks:
  medusa-network:
    driver: bridge

volumes:
  backend-dist:
