services:
  backend:
    build:
      context: ./medusa-backend
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
      - "7000:7000"
      - "7001:7001"
    environment:
      - DATABASE_URL=postgres://TEST:TESTTEST@34.56.60.234:5432/medusa_db
      - JWT_SECRET=something
      - COOKIE_SECRET=something
      - DATABASE_TYPE=postgres
      - ADMIN_CORS=http://localhost:7000,http://localhost:7001
      - STORE_CORS=http://localhost:8000
      - NODE_ENV=development
      - HOST=0.0.0.0

    volumes:
      - ./medusa-backend:/app/backend
      - /app/backend/node_modules
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:9000/health",
        ]
      interval: 30s
      timeout: 5s
      retries: 3
    networks:
      - medusa-network
    restart: unless-stopped

  storefront:
    build:
      context: ./meduse-storefront
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - NEXT_PUBLIC_MEDUSA_BACKEND_URL=http://backend:9000
      - NEXT_PUBLIC_MEDUSA_API_KEY=pk_01JB8DVWNPHW2RASR2MX7D88P7
      - REVALIDATE_WINDOW=10
      - NODE_ENV=development
    volumes:
      - ./meduse-storefront:/app/storefront
      - /app/storefront/node_modules
      - /app/storefront/.next
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - medusa-network
    restart: unless-stopped

networks:
  medusa-network:
    driver: bridge
