version: "3"
services:
  backend:
    build:
      context: ./medusa-backend
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
      - "7001:7001"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - COOKIE_SECRET=${COOKIE_SECRET}
      - DATABASE_TYPE=postgres
      - ADMIN_CORS=http://${IP_ADDRESS}:7700
      - STORE_CORS=http://${IP_ADDRESS}:8000,http://${IP_ADDRESS}:8100
      - NODE_ENV=development
      - HOST=0.0.0.0
    networks:
      - medusa-network
    restart: unless-stopped
  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile
    image: admin:latest
    restart: always
    depends_on:
      - backend
    container_name: medusa-admin
    ports:
      - "7700:7700"
    environment:
      MEDUSA_BACKEND_URL: http://${IP_ADDRESS}:9000
      NODE_OPTIONS: --openssl-legacy-provider
    networks:
      - medusa-network

  storefront:
    build:
      context: ./storefront
      dockerfile: Dockerfile
    ports:
      - "8100:8100"
    environment:
      - NEXT_PUBLIC_MEDUSA_BACKEND_URL=http://${IP_ADDRESS}:9000
      - NEXT_PUBLIC_MEDUSA_API_KEY=${MEDUSA_API_KEY}
      - REVALIDATE_WINDOW=10
      - NODE_ENV=development
    depends_on:
      - backend
    networks:
      - medusa-network
    restart: unless-stopped
networks:
  medusa-network:
    driver: bridge
