version: "3"
services:
  backend:
    build:
      context: ./medusa-backend
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
      - "7000:7000"
      - "7001:7001"
    environment:
      # Conexión directa a la BD usando IP externa
      - DATABASE_URL=postgres://TEST:TESTTEST@34.56.60.234:5432/medusa_db # RECORDAR CAMBIAR LA IP
      - JWT_SECRET=something
      - COOKIE_SECRET=something
      - DATABASE_TYPE=postgres
      - ADMIN_CORS=http://localhost:7000,http://localhost:7001
      - STORE_CORS=http://localhost:8000
    networks:
      - medusa-network

  storefront:
    build:
      context: ./meduse-storefront
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - NEXT_PUBLIC_MEDUSA_BACKEND_URL=http://localhost:9000
      - NEXT_PUBLIC_MEDUSA_API_KEY=pk_01JB8DVWNPHW2RASR2MX7D88P7
      - REVALIDATE_WINDOW=10
    volumes:
      - ./meduse-storefront:/app/storefront
      - /app/storefront/node_modules
      - /app/storefront/.next
    depends_on:
      - backend
    networks:
      - medusa-network

networks:
  medusa-network:
    driver: bridge
